#! /usr/bin/zsh

# Programs



pgrep -x sxhkd > /dev/null || sxhkd &

bspc wm -O Virtual1 Virtual2

bspc monitor Virtual1 -d 1 2 3 4 5
bspc monitor Virtual2 -d 6 7 8 9 10

bspc config border_width         4
#bspc config border_radius        25
bspc config window_gap         7

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Opera desktop='^1'
bspc rule -a discord desktop='^7'
bspc rule -a Code desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


bspc config normal_border_color		      "#64737D"
bspc config active_border_color	          "#1e1e1e"
bspc config focused_border_color	      "#133247"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#dd2727"

greenclip daemon &
imwheel &
sxhkd &
setxkbmap -option caps:escape &
/home/mateusz/.screenlayout/default.sh &
/home/mateusz/wallpaper.sh &
~/.config/polybar/launch.sh &